### ISSUE TITLE
support Trusted Publishers

### ISSUE THREAD

**Issue by casperdcl** [casperdcl/deploy-pypi#17]
- `password.required: false`
- `registry-domain.default: https://upload.pypi.org`
- if `password` undefined, generate OIDC "password"
  ```bash
  audience=$(GET $INPUT_REGISTRY_DOMAIN/_/oidc/audience)
  oidc_token=$(GET $ACTIONS_ID_TOKEN_REQUEST_URL -d "$audience" -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq "{token: .value}")
  TWINE_PASSWORD=$(POST $INPUT_REGISTRY_DOMAIN/_/oidc/github/mint-token -d "$oidc_token" | jq -r .token)
  ```

<details><summary>references</summary>

- description: https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers#using-trusted-publishing-with-github-actions
- implementation: https://github.com/pypa/gh-action-pypi-publish/blob/unstable/v1/oidc-exchange.py
- `detect_github(audience) -> oidc_token`: https://github.com/di/id/blob/main/id/_internal/oidc/ambient.py
- GHA env vars: https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

</details>

**Comment by 0x2b3bfa0** [comment]
Would a shell script be enough, or does it have to be pure Python?

```bash
curl --get "$ACTIONS_ID_TOKEN_REQUEST_URL" \
     --header "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
     --data $(curl "https://$REGISTRY_DOMAIN/_/oidc/audience") |
jq "{token: .value}" |
curl "https://$REGISTRY_DOMAIN/_/oidc/github/mint-token" --data @- |
jq --raw-output .value
```

Note that https://github.com/casperdcl/deploy-pypi/issues/17#issue-1893037869 is wrong, and `$REGISTRY_DOMAIN` is the host name of the registry; e.g. `upload.pypi.org`

**Comment by casperdcl** [comment]
shell script is the only thing supported[^single-file]

[^single-file]: https://github.com/casperdcl/deploy-pypi#why "Has the entirety of the code in a [single file](https://github.com/casperdcl/deploy-pypi/blob/master/action.yml), making it very easy to review"

**Comment by casperdcl** [comment]
https://github.com/pypa/gh-action-pypi-publish/blob/a712d989cca7b5d2b239f655efb2512082d5bce8/action.yml#L12-L23

looks like it's meant to be `https://upload.pypi.org`

**Comment by 0x2b3bfa0** [comment]
> _shell script is the only thing supported_

I asked because the only ™️ thing your shell script does is invoking the `python` executable in every conceivable way. Maybe you wanted something along the lines of `python -c 'urllib ...'` instead of `curl` and `jq` for this?

![Rube_Goldberg's__Self-Operating_Napkin__(cropped)](https://github.com/casperdcl/deploy-pypi/assets/11387611/92a49d56-04e2-4d4c-ac7a-a868c2bc3062)

**Comment by 0x2b3bfa0** [comment]
> _looks like it's meant to be https://upload.pypi.org_

It also works with `pypi.org` but you're right; updated!

**Comment by webknjaz** [comment]
FTR, in #22 I mentioned that using OIDC like this is insecure.

**Comment by casperdcl** [comment]
Thanks; updated the README guidance - let me know if it still seems insecure :)
